language: cpp
sudo: false
dist: trusty

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Debug VERBOSE=1
        - os: linux
          compiler: gcc
          env: BUILD_TYPE=Release VERBOSE=1
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Debug VERBOSE=1
        - os: linux
          compiler: clang
          env: BUILD_TYPE=Release VERBOSE=1

install:
    - sudo apt-get install libzmq-dev

script: ./build.sh

notifications:
  email: false
